# Generated by Django 3.1.6 on 2021-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
